//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Boarrd_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class boardDBEntities : DbContext
    {
        public boardDBEntities()
            : base("name=boardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_draw_rules> tbl_draw_rules { get; set; }
        public virtual DbSet<tbl_elements_in_group_draw> tbl_elements_in_group_draw { get; set; }
        public virtual DbSet<tbl_groups> tbl_groups { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
