//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Boarrd_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_groups
    {
        public tbl_groups()
        {
        }

        public tbl_groups(int _group_id, string _group_name)
        {
            this.group_id = _group_id;
            this.group_name = _group_name;
        }
        public int group_id { get; set; }
        public string group_name { get; set; }
    
    }
}
