//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Boarrd_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_draw_rules
    {
        public int max_number_of_elements_per_user_per_day { get; set; }
        public tbl_draw_rules(int _max_number_of_elements_per_user_per_day)
        {
            this.max_number_of_elements_per_user_per_day = _max_number_of_elements_per_user_per_day;
        }
    }
}
