//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Boarrd_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public tbl_users()
        {
        }
        public tbl_users(int _user_id, string _username, string _password, string _ip, string _useragent, string _type)
        {
            this.user_id = _user_id;
            this.username = _username;
            this.password = _password;
            this.ip = _ip;
            this.useragent = _useragent;
            this.type = _type;
        }

        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string ip { get; set; }
        public string useragent { get; set; }
        public string type { get; set; }
    
    }
}
