//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Boarrd_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_elements_in_group_draw
    {
        public int group_id { get; set; }
        public int startPointX { get; set; }
        public int startPointY { get; set; }
        public int endPointX { get; set; }
        public int endPointY { get; set; }
        public string color { get; set; }
        public string element_type { get; set; }
        public int user_id { get; set; }
        public string time_added { get; set; }
    
        public tbl_elements_in_group_draw(int groupID, int startPointX, int startPointY, int endPointX, int endPointY, string color, string curElementType, DateTime now, int user_id)
        {
            this.group_id = groupID;
            this.startPointX = startPointX;
            this.startPointY = startPointY;
            this.endPointX = endPointX;
            this.endPointY = endPointY;
            this.color = color;
            this.element_type = curElementType;
            this.time_added = now.ToString();
            this.user_id = user_id;
        }
        public tbl_elements_in_group_draw()
        {

        }
    }
}
